name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terragrunt:
    name: Provision
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: Test Action
        run: |
          npm ci
          npm run build --if-present
          npm test
