name: Branch
on:
  push:
    branches-ignore: [main]

jobs:
  terragrunt:
    name: Provision
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Test Action
        run: |
          npm ci
          npm run build --if-present
          npm test
      - name: Build Action
        run: |
          npm i -g @vercel/ncc
          ncc build index.js --license licenses.txt

