name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terragrunt:
    name: Provision
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Test Action
        run: |
          npm ci
          npm run build --if-present
          npm test
      - name: Build Action
        run: |
          npm i -g @vercel/ncc
          ncc build action.js --license licenses.txt
      - name: Create Version
        id: version
        run: echo "::set-output name=number::$(date +%s)"
      - name: Tag Release
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.number }}
